LLNL/maestrowf

maestrowf/datastructures/core/parameters.py, maestrowf/datastructures/core/study.py, maestrowf/datastructures/core/studyenvironment.py
All studies currently need parameters. This PR adds a feature that allows for a specification to not include a set of parameters which creates a strictly linear, one time execution, study.
=> Ability to Create Linear Studies without Parameters

maestrowf/datastructures/core/studyenvironment.py, maestrowf/datastructures/environment/variable.py
This PR addresses the issue in #32. The bug was just a small issue where the StudyEnvironment was not accounting for the possibility of getting an integer. The fix was simple:
* Check that a substitution is a string and that it has a variable token in it. If so, it's a label. If it's not a string or it doesn't have the token, treat it as a straight replacement.
* The Variable class now has to cast the value to a string for substitutions.
=> Minor tweaks for capturing integers in the environment.

maestrowf/maestro.py
Adds the $(SPECROOT) keyword for referring to the path in which the study specification is loaded from.
Signed-off-by: Francesco Di Natale <dinatale3@llnl.gov>
=> Addition of the SPECROOT to variables when a spec is parsed.

maestrowf/interfaces/script/localscriptadapter.py
logger.warning uses % to perform string formatting. % does
not support new style string formatting with {}.
=> Correct logger.warning call in localscriptadapter

maestrowf/datastructures/core/executiongraph.py
A state of FINISHED must be provided to record.mark_end when a step
is complete in execute_ready_steps.
Signed-off-by: Giuseppe Di Natale <dinatale2@llnl.gov>
=> Properly mark step finished in execute_ready_steps

maestrowf/abstracts/enums/__init__.py, maestrowf/abstracts/interfaces/scriptadapter.py, maestrowf/conductor.py, maestrowf/datastructures/core/executiongraph.py, maestrowf/interfaces/script/localscriptadapter.py, maestrowf/interfaces/script/slurmscriptadapter.py, maestrowf/maestro.py
Allow a user to request that a study be cancelled. Maestro will
generate a cancel.lock file to signal the conductor to cancel all
remaining jobs. Add functionality to cancel jobs to the scriptadaptor
interface and implement the functionality in both the local and slurm
script adapters.
Signed-off-by: Giuseppe Di Natale <dinatale2@llnl.gov>
=> Implementation of study cancellation

maestrowf/maestro.py
Use argparse's subparser functionality to implement a "run" and
"status" subcommand. This lays the infrastructure necessary for
future subcommands and is overall cleaner.
TODO - I still need to sort out the use of `setup_logging`.
=> Introduce subparsers for subcommands

maestrowf/interfaces/script/slurmscriptadapter.py
Corrects a bug in the Slurm adapter that causes a blank nodes value in the submission script header if the number of nodes is not specified in a study step.
=> Correction of a bug when detecting if a step sets node.

maestrowf/maestro.py
Introduce autono option for auto answering prompts as
no. Essentially, autono is a dry run option.
Having this ability is also useful for CI.
Signed-off-by: Giuseppe Di Natale <dinatale2@llnl.gov>
=> Add an autono option to allow for dry runs

maestrowf/maestro.py
Allow the user to control the number of times a job can be submitted
to the scheduler.
=> Introduce control for number of job resubmissions

maestrowf/abstracts/interfaces/schedulerscriptadapter.py, maestrowf/interfaces/script/slurmscriptadapter.py, samples/documentation/launcher_tokens.yaml
This PR continues to support the legacy notation of $(LAUNCHER)[n,p],
where n is the number of nodes a command requires and p is the number
of processors. This notation is expanded to loosen the requirement for
nodes (except in the legacy notation above) and changes the notation to
allow for more flexibility (nodes and processors can be notated out of
the above order). The new notations becomes $(LAUNCHER)[#n, #p] where
'#n' is not required ($(LAUNCHER)[#p] is also valid). See the study in
samples/documentation/launcher_tokens.yaml. Closes #30.
Initial logic and new regex.
Logic for parsing out launcher tokens.
Addition of a case for when launcher token appears on its own.
Update to the SLURM adapter to supposed unset node counts.
Added launcher token documentation study file.
Bug fixes …
=> Adds support for enhanced launcher token notations.

maestrowf/datastructures/core/executiongraph.py
The `ExecutionGraph` previously used a method called `_submit_record`. During the time where local execution was introduced, the code was cleaned up with a method called `_execute_record`. This PR simply replaces the old method with the new one.
=> Fixes a bug where restart logic uses the old _submit_record method.

maestrowf/interfaces/script/slurmscriptadapter.py
Corrects a minor bug that causes the SLURM cancel to return an abnormal CancelCode exit by running the cancel command with an empty job ID list.
=> Fix to correct passing an empty jobid list to SLURM cancel.

maestrowf/abstracts/interfaces/schedulerscriptadapter.py, maestrowf/datastructures/core/study.py, maestrowf/interfaces/script/slurmscriptadapter.py
This PR was originally meant to just add reservations, but the abstract interfaces needed to be updated to support it. There were updates and some clean up to the abstract `SchedulerScriptAdapter` and `ScriptAdapter`. The `SchedulerScriptAdapter` now passes a `**kwargs` parameter to support a more flexible range of parameters.
NOTE: This PR is a precursor to a wider change to how resources will be specified in the specification per step.
=> Adds the ability to specify reservations and other scheduling parameters.

maestrowf/abstracts/interfaces/schedulerscriptadapter.py
The previous assumption was that a user submitting would ALWAYS want to use an MPI implementation. However, there are use cases that a user might want to submit a threaded job that doesn't use MPI to a cluster/server farm. The grounds for the initial assumption are therefore broken and so the condition where a launcher token is not seen now returns just the command itself.
=> Removal of the prepend assumption for remote launching.

maestrowf/abstracts/interfaces/schedulerscriptadapter.py, maestrowf/datastructures/core/executiongraph.py, maestrowf/datastructures/core/study.py, maestrowf/datastructures/dag.py, maestrowf/interfaces/script/slurmscriptadapter.py, maestrowf/maestro.py, maestrowf/utils.py, samples/lulesh/lulesh_sample1_macosx.yaml, samples/lulesh/lulesh_sample1_unix.yaml
Previously Maestro used a spanning tree to find all dependent jobs; however, that method suffered from the issue that steps could be expanded before all their dependencies are. This PR makes it so that Maestro topologically sorts all steps before expanding the Study's DAG into an ExecutionGraph.
=> Correction of how dependency ordering happens during study construction.

maestrowf/datastructures/core/executiongraph.py, maestrowf/datastructures/core/study.py, maestrowf/datastructures/core/studyenvironment.py, maestrowf/maestro.py, samples/lulesh/lulesh_sample1_macosx.yaml, samples/lulesh/lulesh_sample1_unix.yaml
Previously, `OUTPUT_PATH` would refer to the study output path during setup and then to a step's local workspace during a study. There are cases where users would want to read or point to the root directory of an executing study. Therefore, the following nomenclature has been added (and some restated for documentation):
`$(SPECROOT)` = The path to the directory where the original specification that launched the study is located.
`$(OUTPUT_PATH)` = During setup, where the timestamped directory is created. Thereafter, the location of the study output root of the executing study.
`$(WORKSPACE)` = For each step definiton, the local workspace of the step.
=> Correct the inability of accessing the study output root directory.

maestrowf/datastructures/core/executiongraph.py, maestrowf/datastructures/core/study.py, maestrowf/datastructures/yamlspecification.py, maestrowf/interfaces/script/fluxscriptadapter.py, maestrowf/interfaces/script/slurmscriptadapter.py
There was a bug that would substitute "cores per task" set to 1 by default as well as placing the value in quotations. Related to this issue, a bad reference to `_restart_limit` in the `_StepRecord` class was also corrected.
=> Correction to handling "cores per task" resource allocation.

maestrowf/datastructures/core/study.py
This PR corrects a bug where we weren't searching for workspaces in the restart portion of a StudyStep.
=> Correction to application of workspaces to restart commands in steps. 

maestrowf/interfaces/script/fluxscriptadapter.py
This PR includes a number of bugfixes for the Flux adapter.
- Addition of the missed "allocated" state
- Enhancement to make it so that the MPI binary is passed via batch
- Addition of the jobid to logging on submission
=> Flux for Spectrum bugfixes

maestrowf/conductor.py, maestrowf/datastructures/core/study.py, maestrowf/datastructures/yamlspecification.py
This pull request addresses ticket #124: BaseException.message has been deprecated as of Python 2.6.
=> Updated exception messages

maestrowf/datastructures/core/executiongraph.py
Addresses issue #126, improper text writeout in ExecutionGraph's write_status method.
=> Fix status.csv 'State' column writeout.

maestrowf/datastructures/core/parameters.py, maestrowf/datastructures/core/study.py, maestrowf/maestro.py, samples/parameterization/custom_generator.py, samples/parameterization/lulesh_custom_gen.py
This PR adds the ability for a user to use custom code for generating parameters. In all cases, metadata about parameters is now dumped. In order to use this feature, a user simply uses the command line ```maestro run --pgen <path to .py> <path to study YAML>```. Within the file specified by the ```--pgen``` flag, the function `get_custom_generator()` must be defined and must return a `ParameterGenerator` instance.
=> Addition of custom parameter generation when running studies.

maestrowf/datastructures/core/executiongraph.py, maestrowf/datastructures/core/study.py
This PR addresses the issue in #134 which exposed a bug in passing study description information to the `ExecutionGraph`. The API has been updated to have required `name` and `description`, and then adds the `**kwargs` parameter. The change allows the `Study` class to use the API as it did before while also carrying any extra information. Additionally, there is now a `log_description` method that the `Study` now calls to log study description information to the output log in the study's work space.
=> More flexible ExecutionGraph description API and logging of description.

maestrowf/datastructures/core/executiongraph.py
Originally from https://github.com/LLNL/maestrowf/pull/133#issuecomment-413932611:
@jsemler -- Alright, after a good bit of digging around, I think I've narrowed the bug down. I apologize if this explanation is somewhat convoluted, but I'll do what I can to make it clear.
In the `ExecutionGraph` method `execute_ready_steps`, there are a number of back end sets that track various aspects of execution, including failed steps, in progress steps, completed steps, dependency completions, and various other things (which for this discussion aren't important). The major thing that gets tracked are the ready steps which are in a `deque` object. When a step is deemed to be ready, its `StepRecord` object is pushed to the `ready_steps` queue. However, in the `execute_ready_steps` method, the …
=> Throttled workflows push steps into the ready queue multiple times.

maestrowf/datastructures/environment/gitdependency.py, maestrowf/interfaces/script/localscriptadapter.py, maestrowf/interfaces/script/slurmscriptadapter.py, maestrowf/maestro.py, maestrowf/utils.py
Addition of a `start_process` utility method to centralize how processes are opened. Fixes #142.
=> Fixes Popen output to use universal newlines.

README.md
This PR is a continuation of documentation updates. Please provide feedback as things are committed.
=> README tweak to update quickstart link.

maestrowf/datastructures/core/study.py, maestrowf/maestro.py, maestrowf/utils.py
Previously whenever the study name in a specification had a space, it'd cause the conductor to fail silently. `make_safe_path` had been added previously just taking a list of arguments and wasn't clearly defined. So this PR corrects all use of pathing to make use of the new `make_safe_path` which now takes as arguments a `base_path` which is assumed to be a valid path to use as a baseline and then makes the items in `*[args]` path safe and joins them to the base path. This new definition allows for a user to make safe paths without having to pass a full path to the function or call `os.path.join` externally.
=> Correction to safe pathing for missed cases and make_safe_path enhancements.

maestrowf/datastructures/core/executiongraph.py, maestrowf/utils.py
Fixes #159 -- long running jobs can reach the day range and breaks the formatted print because the time difference contains a comma.
=> Correction to fix the format of output status time to avoid a comma that breaks printing.

maestrowf/datastructures/core/study.py, samples/lulesh/lulesh_sample1_macosx_linear.yaml, samples/lulesh/lulesh_sample1_unix_linear.yaml, setup.py
@tadesautels and @jsemler both ran into the same bug related to linear study staging. It seems that the previous `_stage_linear` in the `Study` class was outdated since the new `_stage_parameterized` was introduced. It seems like it was entirely an oversight, but it now seems like it's redundant since the parameterized staging is general enough to handle both cases. The simplest solution to this bug seems to just move `_stage_parameterized` to be the general solution and to remove `_stage_linear` entirely.
@tadesautels and @jsemler -- Can you two confirm that this fix works for the studies that triggered your bug?
=> Removal of _stage_linear since it is now not needed.

maestrowf/maestro.py, maestrowf/utils.py, samples/parameterization/lulesh_montecarlo_args.py, setup.py
This PR adds the functionality to pass arguments to a user specified parameter generating code (the `pgen` CLI parameter). A user can specify multiple `--pargs` command line options to pass in multiple parameters. There is now an example of a randomized "Monte Carlo"-esque LULESH example that accepts parameters.
```maestro run -p ./samples/parameterization/lulesh_montecarlo_args.py --pargs "trials:50" --pargs "smin:10" --pargs "smax:50" --pargs "iter:100" ./samples/lulesh/lulesh_sample1_macosx.yaml```
The command line above runs an example where the size of a simulation is randomly generated between a min of 10 and a max of 50 over 50 trials with each being run for 100 iterations.
=> Addition of pargs for passing parameters to custom parameter generation

samples/lulesh/lulesh_sample1_unix.yaml
Last line to the out.log in post-process-lulesh-trials was overwriting the log file, needed a `>>` instead of a `>`
Signed-off-by: Peter Robinson <robinson96@llnl.gov>
=> do not overwrite log file in the lulesh unix example

maestrowf/datastructures/core/study.py
This PR implements an enhancement to the metadata file such that all steps in the workspace and step combinations metadata file contain relative paths to the `_source` (global study workspace). The change makes it so that users can use the metadata to index relative to the study root with external tools. It also makes it so that a user can search for particular workspaces in the step combinations hierarchy.
=> Enhancements to store relative pathing in the metadata file.

samples/lulesh/lulesh_sample1_macosx.yaml, samples/lulesh/lulesh_sample1_unix.yaml, samples/lulesh/lulesh_sample1_unix_slurm.yaml
The LULESH repository has been updated, so updating the Maestro examples to force the version to the 2.0.3 tag since the specifications here rely on it.
=> Addition of tag to LULESH git dependency.

Pipfile, Pipfile.lock, setup.py
There is a known vulnerability in PyYAML version >= 2.4b1 -- this PR adds the fix so that pip and Pipenv install the versions that fulfill the condition to fix the vulnerability.
=> PyYAML vulnerability fix

maestrowf/abstracts/interfaces/schedulerscriptadapter.py, maestrowf/abstracts/interfaces/scriptadapter.py, maestrowf/interfaces/script/fluxscriptadapter.py, maestrowf/interfaces/script/localscriptadapter.py, maestrowf/interfaces/script/slurmscriptadapter.py, maestrowf/maestro.py, samples/lulesh/lulesh_sample1_macosx.yaml
This extends #181 to allow for shells to be specified for all other adapters by guaranteeing that the shell parameter is popped in the base `ScriptAdapter` base class.
=> Enhance shell batch setting to apply to scheduler scripts.

maestrowf/abstracts/containers/__init__.py, maestrowf/datastructures/core/executiongraph.py, maestrowf/interfaces/script/__init__.py, maestrowf/interfaces/script/localscriptadapter.py, maestrowf/interfaces/script/slurmscriptadapter.py
After some discussion with @lucpeterson @jsemler @koning @robinson96 , it was decided that adapters should rely on `Record` classes to improve the ability of adapters to pass back extra information. Their use case is specifically referring to the `submit` method of adapters, but the notion of records is useful to all adapter calls. I've gone ahead and ported all methods to a record class.
=> Change to transition adapter returns to Record objects.

maestrowf/abstracts/specification.py, maestrowf/datastructures/yamlspecification.py
As mentioned in #197, the `load_specification` method handled loading a specification from a file. The method previously would open the filestream, load the contents and parse to a `Specification` object instance. This method has been broken down into two components now: `load_specification` to load from a file and `load specification_from_stream` to load from raw streams.
This serves two purposes: a. it fulfills the use case in #197 such that Maestro can be used now to programmatically generate specifications and get `Specification` objects from them (in the library use case) and b. it breaks down the larger functionality present to smaller functionality (design principles).
@ben-bay -- Feel free to test/offer feedback here.
=> Extend the Specification interface to break out loading from streams.

maestrowf/interfaces/script/slurmscriptadapter.py
This corrects the ordering issue discovered in #201.
=> Moved SLURM parameters to be placed in front of the submitted script.

maestrowf/maestro.py, samples/lulesh/lulesh_sample1_macosx.yaml, samples/lulesh/lulesh_sample1_unix.yaml, samples/parameterization/custom_generator.py, samples/parameterization/lulesh_custom_gen.py, samples/parameterization/lulesh_montecarlo_args.py
Previously, custom parameter generators were unaware of the environment defined in a study specification. This PR tweaks that so that the `StudyEnvironment` data structure is passed to the pgen function so that variables can be consistently defined between the specification and pgen.
This change enables studies which might rely on constructing a list of items in a directory to generate parameters, study specified defaults for parameters, and implementation/method switching (just to name a few).
=> Enhances pgen to take in the environment specified in a study.

maestrowf/datastructures/core/executiongraph.py, maestrowf/datastructures/core/study.py
This PR fixes the bug found in #217 -- Workspace substitutions were overlooked for the `restart` part of the `cmd` entries in steps.
=> Applies workspace substitution to the restart command.

maestrowf/interfaces/script/slurmscriptadapter.py
Fixes #213 
While the SLURM adapter did set the job name when submitting to the scheduler, it had initially been assumed that the logs would be output in the same format as the name. That assumption was proven false, so now we explicitly set the name of both the error and output logs.
=> Sets log and err out for SLURM to parameterized step name

maestrowf/datastructures/core/executiongraph.py, maestrowf/datastructures/core/study.py, setup.py
This PR is meant to improve the number of parameters that DAG expansion can handle. Some initial testing showed that cycle detection really slowed things down. Since the `ExecutionGraph` is technically cookie cut from the `Study` class (derived from a `DAG`), if the initial set of abstract steps doesn't contain a cycle, the expansion will retain that property.
There's something that I ran into as the initial solution I'm proposing is to monkey patch the `ExecutionGraph` to pass on the `detect_cycle` call.  The monkey patching works perfectly for Python3 ; however, the Python2.7 pickle library doesn't seem to be able to handle the pickling of instance methods. I hate to introduce a new dependency, but online folks seem to have settled on `dill` as a more flexible pickler that is capable of …
=> Improve the performance of expansion

maestrowf/interfaces/script/localscriptadapter.py
This PR should fix #240 -- previously the log name was constructed in a fixed format without a unique identifier. This simply adds the PID to the log names.
=> Fix to add PID to local log names.

.pre-commit-config.yaml, Pipfile, requirements.txt
Added pre-commit to enable flake8 checks before a commit is accepted. This ensures that checked in code passes flake8 before it is ever allowed the be commited. 
Pre-Commit can also be used to sort imports and reformat code using isort and black respectively.
Also reordered requirements.txt to more easily determine which are for development.
=> Pre-Commit Checks

MANIFEST.in, maestrowf/datastructures/schemas.json, maestrowf/datastructures/yamlspecification.py, maestrowf/maestro.py, requirements.txt, setup.py
This is my first attempt at adding valid key checking to Maestro. Why? Because indentation slip ups and typos can screw up a yaml spec. Worse, this type of error can be difficult to trace.
P.S. I'm sure I missed some keys that Maestro supports in `step.cmd`, so make sure to remind me of those.
P.P.S. Your `logger` appears to be broken. You'll only see this working for now if you replace my `logger.warning` with a `print`.
P.P.P.S. Speaking of logging, have you considered using color? Merlin is using the open source library [coloredlogs](https://pypi.org/project/coloredlogs/).
=> Added checks for invalid keys.

maestrowf/conductor.py, maestrowf/datastructures/core/study.py, maestrowf/datastructures/core/studyenvironment.py, maestrowf/maestro.py, maestrowf/utils.py, requirements.txt, setup.py
Featuring: colors and minimalism. Addresses #248
=> log improvements

maestrowf/datastructures/schemas.json, maestrowf/datastructures/yamlspecification.py
This wasn't directly related to `jsonschema`, it was just a `KeyError` in our spec verification code. But this did uncover a teeny schema bug.
=> No "variables" bugfix

maestrowf/abstracts/enums/__init__.py, maestrowf/datastructures/core/executiongraph.py, maestrowf/datastructures/core/study.py, maestrowf/maestro.py
This PR adds a simple dry run that forces Maestro to skip scheduler status checking, execution, and generates all workspaces and scripts so that users can see what's generated before kicking off studies. Closes #228.
=> Addition of a simple dry-run capability.

maestrowf/datastructures/schemas.json, maestrowf/interfaces/script/slurmscriptadapter.py, requirements.txt, samples/lulesh/lulesh_sample1_unix_slurm.yaml, setup.py
Adds the ability to specify GPUs, fixes reservation pairing with accounts, and now uses a ChainMap to handle the internal key conflicts between the batch and step settings. Also introduces the exclusive key. Changed to full parameter names for clarity.
Closes #239. Might be useful for #234.
=> Tweaks and fixes to the SLURM header.

maestrowf/datastructures/core/executiongraph.py, maestrowf/utils.py
The main reason to do this was to improve the formatting of `maestro status`. 
An alternate solution would be to modify the getters, or status read and write, but this solution is a little cleaner and faster, and it has the same result. 
If there is a use case that needs more precise datetime stamps, other solutions could be considered. 
And, to give credit where credit is due: 
https://stackoverflow.com/questions/47792242/rounding-time-off-to-the-nearest-second-python.
=> modified executiongraph to round datetimes to nearest second

maestrowf/datastructures/core/executiongraph.py, maestrowf/utils.py
Fixes #264 -- After some testing it appears SLURM loses track of the jobs when in completing state because the system runs out of memory and aborts them. I think it might be reasonable to assume that if you can't find the status, then it likely was killed for some abnormal reason as I do have jobs that seem to successfully finished.
Previously: If SLURM is not caching state properly, but steps
are found to be in FINISHING previous state when seen as UNKNOWN,
mark them complete. Otherwise, mark it unknown, and let the next
step run and fail if the UNKNOWN step failed.
=> Adds a check for UNKNOWN state.

docs/source/index.rst
Added introduction documentation from the README.md file.
=> Added introduction documentation

maestrowf/interfaces/script/lsfscriptadapter.py
When computing CPUs per node on LSF.
=> Bugfix: Division by string instead of number

maestrowf/conductor.py, maestrowf/maestro.py
This PR addresses the feature request #257
=> Addition of processing multiple directories and globs for status

.travis.yml, tox.ini
Maestro will be dropping support for Python 2 in the upcoming release. This PR updates the tests since the `setup.py` file has now been updated and it's causing TravisCI failures in PRs.
=> Removal of Python 2.7 and addition of newer Python 3 versions

maestrowf/specification/yamlspecification.py
While writing unit tests found a bug that in YAMLSpecification the desc property setter actually changes the name property not description.
=> simple bug fix in the YAMLSpec description setter

maestrowf/abstracts/interfaces/scriptadapter.py, maestrowf/datastructures/core/executiongraph.py, maestrowf/datastructures/core/study.py, maestrowf/interfaces/script/fluxscriptadapter.py, maestrowf/interfaces/script/localscriptadapter.py, maestrowf/interfaces/script/lsfscriptadapter.py, maestrowf/interfaces/script/slurmscriptadapter.py
There now needs to be an aliasing of nickname with a step name when requested because adapters expect to use the name. StudyStep objects now return their nickname if the nickname is set. Objects such as the ExecutionGraph must now use the real_name for logistic tracking, while adapters can continue to use name. The nickname field is then used to fill in hashing nicknames to correct the script generation.
Fixes #291
Fixes #267
=> Add name and real_name StudyStep properties.

maestrowf/datastructures/environment/gitdependency.py
Fixes #326 
Corrects the use of `Popen.wait` to `Popen.communicate` to prevent a timeout due to a buffering issue that causes a process to hang once the buffer becomes full.
=> A fix to the GitDependency that prevents a timeout on repository status checking

.travis.yml, pyproject.toml, setup.py, tox.ini
Python 3.5 is retired and no longer updated -- dropping testing/support for 3.5.
=> Removal of Python3.5 from testing

maestrowf/maestro.py
The `maestro cancel` subcommand now accepts globbing and multiple paths for cancellation. It simply places a cancel lock in each directory just as it did for a single directory previously. Additionally, it will ask the user if they are sure they would like to kill the printed directories before actually canceling.
=> Addition of cancellation for multiple directories and globs.

pyproject.toml
This PR is trying to fix the new 3.6 `cryptography` error that's been popping up.
=> Draft: Update pip and tox for 3.6

maestrowf/abstracts/interfaces/flux.py, maestrowf/interfaces/script/_flux/flux0_17_0.py, maestrowf/interfaces/script/_flux/flux0_18_0.py, maestrowf/interfaces/script/_flux/flux0_26_0.py, maestrowf/interfaces/script/fluxscriptadapter.py
This PR adds several changes to the 0.26.0 adapter based on experiences with the GMD loop.  In particular:
- set the default value for `force_broker` to `True` to maximize compatibility with other schedulers/backends
- handle errors in the type for `ngpu` in the flux adapter
- flux the number of slots used in the nested Flux case
- add version checking and log an error when the versions (broker vs adapter) are incompatible
I confirmed that the extra logging does not trigger when running 0.26.0 against 0.26.0 and the error is displayed when running against an older Flux (I had 0.19.0 on hand on Pascal):
```
[2021-05-17 21:08:51: DEBUG] [flux0_26_0: 28] New Flux handle created.
[2021-05-17 21:08:51: DEBUG] [flux0_26_0: 32] Connected to Flux broker running version 0.19.0 using maestro …
```
=> Flux update

maestrowf/interfaces/script/_flux/flux0_26_0.py
Recent changes in #359 introduced a bug that only checked for the inclusion of the `gpus` key a step's settings and erroneously allowed the flag's inclusion even when left blank causing malformed scripts to be generated. This PR corrects the underlying checks to exclude the flag in all cases other than when the value is non-zero.
=> Update to fix the addition of -g erroneously to flux mini commands

maestrowf/interfaces/script/_flux/flux0_18_0.py, maestrowf/interfaces/script/_flux/flux0_26_0.py, maestrowf/interfaces/script/fluxscriptadapter.py, maestrowf/specification/schemas/yamlspecification.json
We've recently been hitting a bug where the wall time parsing in the Flux adapter is too rigid and limits a user to a 24 hour cap. Recently, there has been a need to support wall times that are outside the 24 hour range. While fixing the parsing, the wall time can now accept a numeric number of minutes, a 0 for infinite, and colon separated formatting (that now does not need to conform to `HH:MM:SS`).
=> Additional flexibility to walltime parsing for Flux

maestrowf/datastructures/core/executiongraph.py, maestrowf/interfaces/script/_flux/flux0_26_0.py
During a DAT with @jmast and it turns out that Maestro does not catch when the Flux handle sends a connection reset due to a failed connection. This PR adds an exponential back off to resubmission attempts and a try/catch to the `FluxScriptAdapter.`
=> Addition of connection to try/catch to FluxAdapter

samples/documentation/lulesh_sample1_unix_commented.yaml, samples/lulesh/lulesh_sample1_macosx.yaml, samples/lulesh/lulesh_sample1_macosx_linear.yaml, samples/lulesh/lulesh_sample1_unix.yaml, samples/lulesh/lulesh_sample1_unix_linear.yaml, tests/specification/test_specs/lulesh_sample1_unix.yml
I was taking a look at the `Lulesh` example to better understand the inner workings of `maestro` and was a little confused because of the file outputs. I think the changes in this PR are necessary to avoid confusing file outputs.
The results differ in as follows:
**Previous file output:**
```bash
ITER.10.SIZE.10
ITER.10.SIZE.20
ITER.10.SIZE.30
ITER.20.SIZE.10
ITER.20.SIZE.20
ITER.20.SIZE.30
ITER.30.SIZE.10
ITER.30.SIZE.20
ITER.30.SIZE.30
```
**New file output:**
```
Parameterized step that has Parameter Independent dependencies
TRIAL = 2
/Users/tobias/tmp2/maestrowf/tests/lulesh/run-lulesh
ITER.10.SIZE.10
ITER.10.SIZE.20
ITER.10.SIZE.30
ITER.20.SIZE.10
ITER.20.SIZE.20
ITER.20.SIZE.30
ITER.30.SIZE.10
ITER.30.SIZE.20
ITER.30.SIZE.30
```
Hope that makes sense :)
=> Avoid overriding previous lines in Lulesh example

maestrowf/abstracts/enums/__init__.py, maestrowf/abstracts/interfaces/flux.py, maestrowf/abstracts/interfaces/schedulerscriptadapter.py, maestrowf/datastructures/core/parameters.py, maestrowf/interfaces/script/_flux/flux0_26_0.py, maestrowf/interfaces/script/fluxscriptadapter.py, maestrowf/specification/schemas/yamlspecification.json, maestrowf/utils.py, samples/lulesh/lulesh_sample1_unix_flux.yaml
This PR cleans up some things and adds to the `FluxScriptAdapter`:
+ Renamed `use_broker` in the YAML specification to `nested` to better match with Flux's externally used terminology.
+ Addition of `urgency` to the YAML specification for job priority.
+ A fix for `inf` wall time for the `FluxScriptAdapter` that previously caused an exception when dealing with string based digits.
=> Flux Adapter Clean up and Addition of Job Priority

docs/source/index.rst, docs/source/lulesh_breakdown.rst, docs/source/schedulers.rst, maestrowf/datastructures/core/executiongraph.py, maestrowf/interfaces/script/lsfscriptadapter.py, maestrowf/specification/schemas/yamlspecification.json, maestrowf/specification/yamlspecification.py, samples/lulesh/lulesh_sample1_unix_lsf.yaml, tests/interfaces/script/test_lsfscriptadapter.py
Enables more complete specification of jsrun launcher
Adds new step keys to deal with unique resource specification differences that procs/nodes don't fully map to
Overloads cores per task with lsf's  cpus_per_rs to remain backwards compatible with existing yaml specification
=> Enable more complete configurability of jsrun launcher

maestrowf/specification/yamlspecification.py
This PR fixes #391 that causes values other than the empty string to trigger a validation error.
=> Correct conditional to correct empty string catch.

maestrowf/maestro.py
Hi,
Running `maestro` for the first time ever today from the `develop` branch. I first tried `maestro` without anything else, but it resulted in a traceback.
```bash
(venv) kinow@ranma:~/Development/python/workspace/maestrowf$ maestro 
Traceback (most recent call last):
File "/home/kinow/Development/python/workspace/maestrowf/venv/bin/maestro", line 8, in <module>
sys.exit(main())
File "/home/kinow/Development/python/workspace/maestrowf/maestrowf/maestro.py", line 495, in main
if not hastattr(args, 'func'):
NameError: name 'hastattr' is not defined
```
I think it would be best to print the program usage instead? So if users are not aware, or not sure, which subcommand/subparser to trigger, they can read the usage and decide then.
Thanks for maestro! :wave: 
-Bruno
EDIT: closes #188 …
=> Print usage when no args provided

maestrowf/interfaces/script/_flux/flux0_26_0.py
This MR introduces state changes that allow Maestro to work with newer versions of Flux that have new state abbreviations for job status. The change is pulled from @Jmast's comment [here](https://github.com/LLNL/maestrowf/pull/395#issuecomment-1277741739).
=> Introduces additional states for handling new versions of Flux

maestrowf/interfaces/script/lsfscriptadapter.py
fixes a bug where scripts on lsf would start w/o #! in front of the shell
=> no scheduled scripts missig #! on lsf

Dockerfile
Hi!
The Dockerfile placed at "Dockerfile" contains the best practice violation [DL3006](https://github.com/hadolint/hadolint/wiki/DL3006) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3006 occurs when the image tag for the base image is missing.
In this pull request, we propose a fix for that smell generated by our fixing tool. We have verified that the patch is correct before opening the pull request.
To fix this smell, specifically, we use a heuristic approach that selects the most probable version tag for the given base image. In detail, it selects the most recent image tag which corresponds to the same image digest that currently corresponds to the "latest" tag, used by default when pulling the image from DockerHub if a specific image tag is …
=> Fix for Dockerfile smell DL3006

.readthedocs.yaml, mkdocs.yml
Pins mermaid package to last pre 10.x version to restore diagrams broken by 10.x api change
=> Pin mermaid to 9.4 due to api breaking change in 10.x

maestrowf/datastructures/core/executiongraph.py, maestrowf/interfaces/script/_flux/flux0_26_0.py, maestrowf/interfaces/script/_flux/flux0_49_0.py, pyproject.toml
Update 0.49 and 0.26 adapters cancellation to deal with recent update to submit that converts from flux JobID to native types.
Update general cancellation behaviors:
- Check for in progress steps before declaring cancelled successfully to delay until actual final states can be serialized
- Update cancel logic to mirror failure logic: mark all steps downstream of a cancelled step to also be cancelled
=> Fix flux job cancellation

maestrowf/interfaces/script/slurmscriptadapter.py, pyproject.toml, pytest.ini, tests/conftest.py, tests/integration/conftest.py, tests/integration/test_flux.py, tests/integration/test_slurm.py, tests/interfaces/script/test_slurmscriptadapter.py
Slurm adapter bugfixes
* Adds prescribed column lists to both squeue and sacct to avoid parsing issues due to optional user environment variables 'SQUEUE_FORMAT' and 'SACCT_FORMAT'.
* Reduces some unneeded columns in sacct to make it more robust (not all machines have accounts, which broke the parsing)
Test additions
* Enabled detection of slurm scheduler for live test subset (sched_slurm marker) with auto disablement of marked tests to remain quiet in github ci
* Unit tests added for slurm adapter
* check use of squeue and sacct job status checking options in presence of custom squeue/sacct format env vars
* check functionality of job cancellation
* Slurm 'hello world' integration test
=> slurm adapter robustness

docs/Maestro/cli.md, maestrowf/conductor.py, maestrowf/datastructures/core/executiongraph.py, maestrowf/maestro.py, mkdocs.yml, poetry.lock, pyproject.toml, tests/test_cli.py
This feature adds the ability to change some of a study's configuration during execution, including:
- rlimit (restart limit)
- throttle
- sleep
Implementation works like cancel, taking paths to executing study workspaces.  Configuration parameters can be updated either via an interactive prompt for each study workspace given, or using explicit/repeated keyword arguments for each configuration parameter.  
Current Limitations:
- rlimit is a per step configuration, but it is only set globally in current implementation
- If a study is no longer running, updating rlimit will not yet resume the study to account for any increases
=> Update study configuration during execution

.gitignore, docs/Maestro/cli.md, docs/Maestro/how_to_guides/running_with_flux.md, docs/Maestro/parameter_specification.md, docs/Maestro/scheduling.md, docs/Maestro/specification.md, docs/Maestro/tutorials.md, maestrowf/abstracts/interfaces/flux.py, maestrowf/interfaces/script/_flux/flux0_17_0.py, maestrowf/interfaces/script/_flux/flux0_18_0.py, maestrowf/interfaces/script/_flux/flux0_26_0.py, maestrowf/interfaces/script/_flux/flux0_49_0.py, maestrowf/interfaces/script/fluxscriptadapter.py, maestrowf/maestro.py, pytest.ini, samples/hello_world/hello_bye_parameterized_flux.yaml, tests/conftest.py, tests/integration/conftest.py, tests/integration/test_flux.py, tests/utils/test_utils.py
Adds support for attaching the bank, queue fields from the batch block to the flux jobspec.
Adds preliminary support for pass through of arbitrary --setattr flags to the jobspec (attaches to allocation, not flux run's inside the job scripts).
Support added only for newest Maestro flux adapter version, 0.49.0; older versions to be deprecated.
Change default adapter behavior to 'nested: True' so it uses from_nest_command by default.
Fix documentation typos on the cli's pgen args syntax.
Update documentation for running with flux.
=> Make flux adapter aware of banks and queues
