LLNL/maestrowf

- maestrowf/__init__.py
- maestrowf/abstracts/__init__.py
- maestrowf/abstracts/abstractclassmethod.py
- maestrowf/abstracts/envobject.py
- maestrowf/abstracts/graph.py
- maestrowf/abstracts/interfaces/__init__.py
- maestrowf/abstracts/interfaces/scriptadapter.py
- maestrowf/abstracts/simobject.py
- maestrowf/abstracts/specification.py
- maestrowf/conductor.py
- maestrowf/datastructures/__init__.py
- maestrowf/datastructures/core/__init__.py
- maestrowf/datastructures/core/parameters.py
- maestrowf/datastructures/core/study.py
- maestrowf/datastructures/core/studyenvironment.py
- maestrowf/datastructures/dag.py
- maestrowf/datastructures/environment/__init__.py
- maestrowf/datastructures/environment/gitdependency.py
- maestrowf/datastructures/environment/pathdependency.py
- maestrowf/datastructures/environment/script.py
- maestrowf/datastructures/environment/variable.py
- maestrowf/datastructures/yamlspecification.py
- maestrowf/interfaces/__init__.py
- maestrowf/interfaces/script/__init__.py
- maestrowf/interfaces/script/slurmscriptadapter.py
- maestrowf/maestro.py
- maestrowf/utils.py
Corrections to licensing messages in the maestrowf module. This PR is meant to resolve Issue #4
> Addition of the github link to maestrowf.

- maestrowf/datastructures/core/study.py
Previously there was no case checking for a failed job. Maestro
would check and fall through without removing the failed jobs from
the in progress set and eventually loses track of their state. Now
there is a clean up set that flags steps to be marked as failed.
This PR addresses issue #3.
> Addition of a FAILED case when checking for executing jobs.

- maestrowf/datastructures/core/study.py
> Revert "Addition of a FAILED case when checking for executing jobs."

- .travis.yml
- setup.py
Signed-off-by: Ian Lee <lee1001@llnl.gov>
> Updated travis.yml to include python 3.4 and 3.5

- Makefile
- README.md
This pull request handles the makefile clean up specified in issue #7
> Makefile cleanup

- maestrowf/abstracts/interfaces/scriptadapter.py
Corrects the restart bug fix described in #35
> Correction of a variable name that incorrectly set restart to cmd.

- release.sh
- setup.cfg
Addition of an automated release process shell script.
> First pass at a release shell script.

- maestrowf/datastructures/core/parameters.py
- maestrowf/datastructures/core/study.py
This PR addresses the issue of studies that have steps which may not use all of the specified parameters. Previously, Maestro would execute every combination of parameters -- this PR changes the mechanics to check for just the parameters used by each step (and their parents). Along with the change in mechanics, we now need to be able to refer to the workspaces of other steps because they will no longer be named in the same consistent fashion.
> Rework of Parameterization to construct the ExecutionGraph based on used parameters.

- maestrowf/datastructures/yamlspecification.py
- setup.py
Correct the typo for 'description' in various places.
> Correct typoed 'description' in various places

- maestrowf/conductor.py
- maestrowf/datastructures/core/executiongraph.py
- maestrowf/maestro.py
- maestrowf/utils.py
- requirements.txt
- setup.py
An improvement that generates a csv file in a study output directory. The current interface is simply the command ```maestro -s <study directory path>``` which pretty prints the csv in the specified directory.
> Status tracking

- .travis.yml
- docs/source/conf.py
To enforce good python coding practices, add
flake8 as part of testing with TravisCI.
Signed-off-by: Giuseppe Di Natale <dinatale2@llnl.gov>
> Run flake8 on pull requests

- .github/CONTRIBUTING.md
Provide a basic set of contributing guidelines for future contributions.
> Introduce Contributing Guidelines

- maestrowf/datastructures/core/study.py
Addition of workspace substitutions for linear workflows. It somehow got overlooked in the last release.
> Addition of workspace sub to linear studies.

- README.md
Updated the getting started documentation to reflect the most recent features.
> Updated the getting started documentation

- docs/source/getting_started.rst
- docs/source/index.rst
Added initial getting started example documentation.
> Sphinx Documentation

- maestrowf/maestro.py
Fixed a workflow setup issue caused by spaces in the spec name.
> Workflow setup fix

- samples/lulesh/lulesh_sample1_macosx.yaml
- samples/lulesh/lulesh_sample1_unix.yaml
Updated the LULESH examples to use the LULESH git repository for cloning the repo.
> Updated LULESH examples

- maestrowf/interfaces/script/fluxscriptadapter.py
Some minor additional logging and tweaks for additional debugging and information in the Flux Spectrum adapter.
> Additional debug logging for the Flux Spectrum Adapter

- maestrowf/abstracts/enums/__init__.py
- maestrowf/conductor.py
- maestrowf/datastructures/core/executiongraph.py
- maestrowf/maestro.py
These are the changes we discussed.
> #107 Enhance/return codes

- docs/source/index.rst
- docs/source/lulesh_breakdown.rst
- docs/source/maestro_core.rst
- docs/source/quick_start.rst
This PR adds a quick start guide for explaining the basics of how to use Maestro to run the provided LULESH sample specification.
> Addition of Quick Start documentation.

- maestrowf/datastructures/environment/variable.py
> Fix to Variable verification.

- README.md
- docs/source/getting_started.rst
- docs/source/index.rst
- docs/source/lulesh_breakdown.rst
- docs/source/maestro_core.rst
- docs/source/quick_start.rst
- samples/documentation/lulesh_sample1_unix_commented.yaml
This PR is for updates to documentation in general. I've started things off with an update to the README.
I'd like to roll other documentation PRs into this one if possible so that documentation can be updated all at once.
> Updates to Maestro documentation

- maestrowf/datastructures/core/study.py
- maestrowf/maestro.py
This PR introduces hashing of the combination substrings for steps that use parameters in parameterized studies. I've settled for md5 since it produces the shortest strings.
> Addition of user enabled workspace hashing

- maestrowf/interfaces/__init__.py
- maestrowf/interfaces/script/__init__.py
- maestrowf/interfaces/script/fluxscriptadapter.py
Previously we were using a flux ScriptAdapter that was specialized to an in development version of Spectrum. This new adapter is a more generalized version that works with flux instances that are stood up and configured to run as one would expect.
> More generalized FluxScriptAdapter

- maestrowf/datastructures/core/executiongraph.py
> typos. fixes #141

- maestrowf/maestro.py
Added a confirmation message after successfully launching a study.
> Added study confirmation message

- requirements.txt
Added the PyYaml >= 4.2b1 to requirements.txt
> PyYAML vulnerability fix - also in requirements.txt

- maestrowf/datastructures/yamlspecification.py
Fixes the pyYAML vulnerability warning mentioned by @lucpeterson and closes #173
> Addition of a loader to the yaml load call.

- Dockerfile
- docs/source/getting_started.rst
Added a Dockerfile to allow someone to just checkout the repository and play with Maestro without touching their system.
TODO: This isn't quite done yet because I want to add to the Quick Start guide a section on how to just build and run the container and mess with it.
> Addition of a Dockerfile for tutorials and ease of trying out.

- maestrowf/datastructures/environment/gitdependency.py
Corrections the malformed log statements in the `GitDependency` class.
> Tweaks to fix malformed log statements.

- maestrowf/datastructures/core/study.py
This PR is a small tweak that dumps the initial environment that Maestro is run in to a YAML file in the metadata folder.
> Addition of dumping the environment to a YAML file.

- README.md
My "Hello Neptune!" contribution to this project.
> Adding Neptune to the list on Planets

- README.md
Updated the study step name in the README.md examples to highlight the step name doesn't have to match the study name.
> Updated the study step name in the README.md file

- README.md
Added a link to the documentation in the README.md file.
> Added a link to Maestro's documentation

- requirements.txt
Added dill to the requirements.txt file.
> Added dill pip dependency

- maestrowf/maestro.py
- maestrowf/utils.py
Adds a logging utility class and correctly sets the level of the logging facilities so that logging is consistently applied across all submodules. Closes #246 and closes #135 
@ben-bay -- Please try and apply these to your PR locally as a test and see if this fixes your issue in #243.
> Bugfix for logging that didn't appear in submodules

- maestrowf/interfaces/script/slurmscriptadapter.py
Minor change that will enable easier debugging of slurm batch errors.
> enabled raw sbatch errors to be logged

- setup.py
Adds the README as the long description for the Maestro.
> Addition of README as long description.

- docs/source/hello_world.rst
- docs/source/maestrowf.abstracts.containers.rst
- docs/source/maestrowf.abstracts.enums.rst
- docs/source/maestrowf.abstracts.interfaces.rst
- docs/source/maestrowf.abstracts.rst
- docs/source/maestrowf.datastructures.core.rst
- docs/source/maestrowf.datastructures.environment.rst
- docs/source/maestrowf.datastructures.rst
- docs/source/maestrowf.interfaces.rst
- docs/source/maestrowf.interfaces.script.rst
- docs/source/maestrowf.rst
- docs/source/maestrowf.specification.rst
- docs/source/modules.rst
- docs/source/setup.rst
- docs/source/tests.interfaces.rst
- docs/source/tests.interfaces.script.rst
- docs/source/tests.rst
- maestrowf/abstracts/containers/__init__.py
- maestrowf/datastructures/core/__init__.py
- maestrowf/datastructures/core/executiongraph.py
- maestrowf/datastructures/core/parameters.py
- maestrowf/datastructures/core/study.py
Corrects a number of docstrings that were improperly indented and recompilation of API docs.
> Correct documentation compilation warnings

- docs/source/index.rst
- docs/source/installing.rst
Updated the documentation for installing Maestro to make it easier to follow the introduction tutorial.
> Updated the documentation for installing Maestro

- Dockerfile
- docs/source/installing.rst
Updated the documentation for building the Docker image and updated the Dockerfile to use Python 3.
> Updated the Dockerfile and documentation

- maestrowf/conductor.py
- maestrowf/datastructures/core/executiongraph.py
https://github.com/LLNL/maestrowf/issues/310
> WIP: Add job identifier to status command

- docs/source/installing.rst
- maestrowf/abstracts/__init__.py
- maestrowf/abstracts/abstractclassmethod.py
- maestrowf/abstracts/envobject.py
- maestrowf/abstracts/interfaces/schedulerscriptadapter.py
- maestrowf/conductor.py
- maestrowf/datastructures/core/parameters.py
- maestrowf/datastructures/core/study.py
- maestrowf/datastructures/dag.py
- maestrowf/datastructures/environment/gitdependency.py
- maestrowf/interfaces/script/__init__.py
- maestrowf/interfaces/script/slurmscriptadapter.py
- maestrowf/maestro.py
- samples/documentation/lulesh_sample1_unix_commented.yaml
- samples/parameterization/lulesh_itertools_pgen.py
- tests/interfaces/test_script_adapter.py
Ran spell check script and found the following typos.
> Fixes #324

- docker/flux/0.26.0/Dockerfile
- maestrowf/interfaces/script/__init__.py
- maestrowf/interfaces/script/_flux/flux0_18_0.py
- maestrowf/interfaces/script/_flux/flux0_26_0.py
- samples/lulesh/lulesh_sample1_unix_flux.yaml
Fixes and updates based on the GMD loop work.  This could probably use some testing since the 0.26.0 adaptor was originally based off of a different base branch.  Let me know how you'd like to go about testing @FrankD412.  I'm happy to help setup some flux-based CI testing if you are interested.
> Flux update

- maestrowf/interfaces/script/lsfscriptadapter.py
This PR makes minor tweaks to the `LSFScriptAdapter` to add reservation names to the header of submission scripts when the `reservation` key is present in the batch or step sections. The step value takes precedence, and reservations can be specified per step.
> Addition of reservation to bsub headers.

- docs/index.md
"sproviding" typo fix -> "providing"
> Fix typo on index.md
